version: '3.9'
services:
  postgres:
    container_name: "AhaDB"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backups:/backups
    networks:
      - my-network


networks:
  my-network:
    external:
      name: aha-net
