version: '3.9'
services:
  postgres:
    container_name: "AhaDB"
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/backups:/backups
    networks:
      - my-network

  backend:
    container_name: aha_server
    image: aha_backend
    restart: always
    working_dir: /app
    build: .
    command: yarn run start:prod
    ports:
      - 8000:8000
    volumes:
      - ./.env:/app/.env
    networks:
      - my-network
  
  


networks:
  my-network:
    external:
      name: aha-net
